### PR TITLE
Xrender changes

### PR DESCRIPTION
**Pull request by JMC-design**
Allow pictures to be created from pixmaps.
Allow uploading glyphs that aren't alpha masks to glyphsets.

### CODE REVIEW

**Comment by dkochmanski** [comment]
Please rebase your changes against master

**Comment by JMC-design** [comment]
How would I do that through the web interface, because that's what i've got.

**Comment by dkochmanski** [comment]
I don't know how that could be done via web interface. If you'll find a
way to do it from the shell, that would be:

git rebase -i origin/master
git push --force

The first command will put you in the editor, so it may be wise to set
it to something familiar like emacs or vi (ie `export EDITOR=emacs'). If
you are not able to rebase, then I will take care of it after the
weekend (I'm leaving tomorrow for a few days).

Regards,
Daniel


-- 
Daniel Kochmański ;; aka jackdaniel | Przemyśl, Poland
TurtleWare - Daniel Kochmański      | www.turtleware.eu

"Be the change that you wish to see in the world." - Mahatma Gandhi

**Comment by JMC-design** [comment]
Sorry my local is not in a compatible state. only my github tracks sharplispers.

**Comment by dkochmanski** [comment]
then

git remote add sharplispers git@github.com:sharplispers/clx.git
git fetch sharplispers
git rebase sharplispers/master
git push --force

I hope taht helps.

Johannes Martinez Calzada writes:

> Sorry my local is not in a compatible state. only my github tracks sharplispers.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.


-- 
Daniel Kochmański ;; aka jackdaniel | Przemyśl, Poland
TurtleWare - Daniel Kochmański      | www.turtleware.eu

"Be the change that you wish to see in the world." - Mahatma Gandhi

**Comment by JMC-design** [comment]
This isn't right anyways. find-window-picture-format should still be included in case anybody used it, and the export isn't there. I keep running into errors trying to move only one change.

**Pull request closed without merging**
