### PR TITLE
Unify packages

### LINKED ISSUE #29: clash with cl-opengl
`CLX` clashes with `cl-opengl` because CLX defines a `gl` package and cl-opengl nicknames the package cl-opengl with the name gl.

@cbaggers suggested that having CLX depend on cl-opengl could make sense to resolve this.

[https://github.com/cbaggers/cepl/issues/56]

### PR DESCRIPTION
**Pull request by dkochmanski**
All packages follow common naming convention. Fixes #29.

### CODE REVIEW

**Comment by PuercoPop** [comment]
It would be better to do less in each commit and in each PR, to ease review and revering.

- One commit should just replace all mentions of the GL package with XLIB/GL or XLIB.GL
- 'Style' changes like replacing symbols with uninterned symbols should go into their own commit
- Using a package and removing the package prefix should go into its own commit
- The duplicate file commit should go in its own PR (and merged on the spot as I see no controversy there)

**Comment by dkochmanski** [comment]
OK, how about this?

**Comment by luismbo** [comment]
@dkochmanski looks good.

**Comment by dkochmanski** [comment]
OK, I'm merging it (nobody seems to oppose to this change)

**Pull request merged**
