### PR TITLE
added double buffer, randr, and xc-misc

### PR DESCRIPTION
**Pull request by JMC-design**
Sorry about the directory change, didn't think about how it would affect merging.

I wrote these a while ago but haven't had internet access till now.  Somehow updating my system killed all the commit comments and screwed up the uploading to github so the comments are pretty meaningless.  I would have held off on a pull request till I fixed some stuff up, but my laptop died shortly after uploading and I have no clue when I can get something new to develop on.

XC-MISC
complete but no licence and automatic integration not done, though with the ridiculous amounts of xids reserved shouldn't be a problem.

DBE
Complete, everything works.

RandR
Mostly complete, without internet access and poor documentation I had to implement some of 1.3 and 1.4 from the 20 different headers on my system.  Rotation, resolution changes, gamma, and getting properties all work.  Looks like the events and errors aren't in the version uploaded.  

DRI2
bit of a stub, can't test anything without a token.

COMPOSITE
I'm not even sure this even exists as a standard.   The headers on my system showed conflicting functions and my video card drivers were in a bad state.  SBCL would freeze everytime I tried to get-overlay.  I will fix this as I need something similar for my windowing system, but not working.

MIT-SHM
Doesn't appear to have been uploaded.  Basically complete but can't test without a function to get  a fd for shared memory.  I didn't delve too deep into sbcl internals, but should be trivial to add for someone familiar with the macros that implement mmap and such.

These were all implemented as proof of ability for a crowd funding for implementing xinput and xkb, both of which I need for the 'windowing' system I'm implementing.  Hopefully I find something new to develop on because I really need the money!  I'm also looking at finishing some of xrender, at least the functions I need, and gl and glx, and ultimately replacing the buffer code to 'pipelines' to ease connection to Wayland or whatever else comes along in the future.

Comments welcome on style and quality.

### CODE REVIEW

**Comment by mgi** [comment]
Hi,

I, too, had a start of implementation of XRandR lying on my hard drive. It is not complete but here it is anyway for comparison and maybe idea merging:
```lisp
;;; Implementation of XRandR as described by
;;; http://www.x.org/wiki/Projects/XRandR
;;;

(defpackage :xrandr
  (:use :common-lisp :xlib)
  (:nicknames :rr)
  (:import-from :xlib
                #:data
                #:card8
                #:card8-get
                #:card16
                #:card16-get
                #:card32
                #:card32-get
                #:window-get
                #:sequence-get
		#:string-get
		#:index+
                #:extension-opcode
                #:define-extension
                #:gcontext
                #:resource-id
                #:window-id
                #:cursor
                #:make-cursor
                #:with-buffer-request-and-reply
                #:with-buffer-request
                #:display)
  (:export
   ;; Constants
   #:+major-version+
   #:+minor-version+
   #:+screen-change-notify+
   #:+crtc-change-notify+
   #:+output-change-notify+
   #:+output-property-notify+
   #:+provider-change-notify+
   #:+provider-property-notify+
   #:+resource-change-notify+
   #:+normal+
   #:+left+
   #:+inverted+
   #:+right+
   #:+x-axis+
   #:+y-axis+

   ;; Functions
   #:query-version
   #:select-input
   #:set-screen-config
   #:screen-info
   #:get-screen-size-range

   ;; Interfaces
   #:set-rotation))

(in-package :xrandr)

(define-extension "RANDR")

(defmacro opcode (display)
  `(extension-opcode ,display "RANDR"))

;;; The version we implement
(defconstant +major-version+ 1)
(defconstant +minor-version+ 4)

;;; XRandR opcodes
(defconstant +query-version+ 0)
(defconstant +set-screen-config+ 2)
(defconstant +select-input+ 4)
(defconstant +screen-info+ 5)
;; 1.2
(defconstant +screen-size-range+ 6)
(defconstant +set-screen-size+ 7)
(defconstant +screen-resources+ 8)
(defconstant +output-info+ 9)
(defconstant +list-output-properties+ 10)
(defconstant +query-output-property+ 11)
(defconstant +configure-output-property+ 12)
(defconstant +change-output-property+ 13)
(defconstant +delete-output-property+ 14)
(defconstant +get-output-property+ 15)
(defconstant +create-mode+ 16)
(defconstant +destroy-mode+ 17)
(defconstant +add-output-mode+ 18)
(defconstant +delete-output-mode+ 19)
(defconstant +crtc-info+ 20)
(defconstant +set-crtc-config+ 21)
(defconstant +get-crtc-gamma-size+ 22)
(defconstant +get-crtc-gamma+ 23)
(defconstant +set-crtc-gamma+ 24)
;; 1.3
(defconstant +screen-resources-current+ 25)
(defconstant +set-crtc-transform+ 26)
(defconstant +get-crtc-transform+ 27)
(defconstant +get-panning+ 28)
(defconstant +set-panning+ 29)
(defconstant +set-output-primary+ 30)
(defconstant +get-output-primary+ 31)
;; 1.4
(defconstant +get-providers+ 32)
(defconstant +provider-info+ 33)
(defconstant +set-provider-offload-sink+ 34)
(defconstant +set-provider-output-source+ 35)
(defconstant +list-provider-properties+ 36)
(defconstant +query-provider-property+ 37)
(defconstant +configure-provider-property+ 38)
(defconstant +change-provider-property+ 39)
(defconstant +delete-provider-property+ 40)
(defconstant +get-provider-property+ 41)

;;; Helper macros
(defmacro pincf (place &optional (delta 1))
  "C-style post increment (i++)."
  (let ((inc (gensym))
	(new (gensym))
	(old (gensym)))
    `(let* ((,inc ,delta)
	    (,old ,place)
	    (,new (+ ,place ,inc)))
       (setq ,place ,new)
       ,old)))

(defmacro define-value-to-names (fun-name &rest names)
  (let ((name (gensym)))
    `(defun ,fun-name (value)
       (loop for ,name in ',names
	  when (not (zerop (logand value (symbol-value ,name))))
	  collect ,name))))

;;; Server requests
(defun query-version (display &optional (major +major-version+) (minor +minor-version+))
  "Returns the major and minor version of the server's XRandR
implementation. Should be called before using the extension."
  (declare (type display display))
  (with-buffer-request-and-reply (display (opcode display) nil)
      ((data +query-version+)
       (card32 major)
       (card32 minor))
    (values (card32-get 8)
            (card32-get 12))))

(defconstant +invalid-config-time+ 1)
(defconstant +invalid-time+ 2)
(defconstant +failed+ 3)

(defun set-screen-config (window timestamp config-timestamp size-idx rotation rate)
  (let ((display (drawable-display window))
	(offset 1))
    (with-buffer-request-and-reply (display (opcode display) nil)
	((data +set-screen-config+)
	 (window window)
	 (card32 timestamp)
	 (card32 config-timestamp)
	 (card16 size-idx)
	 (card16 rotation)
	 (card16 rate)
	 (pad16))
      (let ((status (card8-get (pincf offset (+ 1 2 4))))
	    (timestamp (card32-get (pincf offset 4)))
	    (config-timestamp (card32-get (pincf offset 4)))
	    (root (window-get (pincf offset 4)))
	    (subpixelorder (card16-get (pincf offset (+ 2 2 4 4)))))
	(values status timestamp config-timestamp root subpixelorder)))))


(defconstant +screen-change-notify+     #x01)
(defconstant +crtc-change-notify+       #x02)
(defconstant +output-change-notify+     #x04)
(defconstant +output-property-notify+   #x08)
(defconstant +provider-change-notify+   #x10)
(defconstant +provider-property-notify+ #x20)
(defconstant +resource-change-notify+   #x40)
(define-value-to-names val-to-mask +screen-change-notify+ +crtc-change-notify+
		       +output-change-notify+ +output-property-notify+
		       +provider-change-notify+ +provider-property-notify+
		       +resource-change-notify+)
;; Usage:
;; (select-input *root* (logior +screen-change-notify+ +crtc-change-notify+))
(defun select-input (window mask)
  (let ((display (drawable-display window)))
    (with-buffer-request (display (opcode display))
      (data +select-input+)
      (window window)
      (card16 mask))))

(defstruct screen-size
  width
  height
  mm-width
  mm-height
  rates)

(defmethod print-object ((screen-size screen-size) stream)
  (format stream "#<~Dx~D (~Dmmx~Dmm) @~{ ~D~^,~} Hz>"
	  (screen-size-width screen-size)
	  (screen-size-height screen-size)
	  (screen-size-mm-width screen-size)
	  (screen-size-mm-height screen-size)
	  (screen-size-rates screen-size)))

(defconstant +normal+   #x01)
(defconstant +left+     #x02)
(defconstant +inverted+ #x04)
(defconstant +right+    #x08)
(defconstant +x-axis+   #x10)
(defconstant +y-axis+   #x20)
(define-value-to-names val-to-rotation +normal+ +left+ +inverted+ +right+ +x-axis+ +y-axis+)

(defun screen-info (window)
  (let ((display (drawable-display window))
	(offset 1))
    (with-buffer-request-and-reply (display (opcode display) nil)
	((data +screen-info+)
	 (window window))
      (let* ((rotations (card8-get (pincf offset (+ 1 2 4))))
	     (root (window-get (pincf offset 4)))
	     (timestamp (card32-get (pincf offset 4)))
	     (config-timestamp (card32-get (pincf offset 4)))
	     (nsize (card16-get (pincf offset 2)))
	     (size-idx (card16-get (pincf offset 2)))
	     (rotation (card16-get (pincf offset 2)))
	     (rate (card16-get (pincf offset (+ 2 2 2))))
	     (sizes (loop for i below nsize
		       collect (make-screen-size
				:width (card16-get (pincf offset 2))
				:height (card16-get (pincf offset 2))
				:mm-width (card16-get (pincf offset 2))
				:mm-height (card16-get (pincf offset 2))))))
	(loop for i below nsize do
	     (setf (screen-size-rates (nth i sizes))
		   (loop for j below (card16-get (pincf offset 2))
		      collect (card16-get (pincf offset 2)))))
	(values rotations root timestamp config-timestamp size-idx rotation rate sizes)))))

(defun set-rotation (window rotation)
  (multiple-value-bind (rotations root timestamp config-timestamp size-idx curr-rot rate)
      (screen-info window)
    (declare (ignore rotations root curr-rot rate))
    (set-screen-config window timestamp config-timestamp size-idx rotation 0)))

(defun set-size (window size-index)
  (multiple-value-bind (rotations root timestamp config-timestamp curr-size rotation rate)
      (screen-info window)
    (declare (ignore rotations root curr-size rate))
    (set-screen-config window timestamp config-timestamp size-index rotation 0)))

(defun get-screen-size-range (window)
  (let ((display (drawable-display window))
	(offset 8))
    (with-buffer-request-and-reply (display (opcode display) nil)
	((data +screen-size-range+)
	 (window window))
      (let ((min-width (card16-get (pincf offset 2)))
	    (min-height (card16-get (pincf offset 2)))
	    (max-width (card16-get (pincf offset 2)))
	    (max-height (card16-get offset)))
	(values min-width min-height max-width max-height)))))

(defun set-screen-size (window width height mm-width mm-height)
  (let ((display (drawable-display window)))
    (with-buffer-request (display (opcode display))
      (data +set-screen-size+)
      (window window)
      (card16 width)
      (card16 height)
      (card32 mm-width)
      (card32 mm-height))))

(defstruct modeinfo
  id name
  width height
  dot-clock
  h-sync-start h-sync-end h-total h-skew
  v-sync-start v-sync-end v-total
  mode-flags)

(defconstant +h-sync-positive+   #x0001)
(defconstant +h-sync-negative+   #x0002)
(defconstant +v-sync-positive+   #x0004)
(defconstant +v-sync-negative+   #x0008)
(defconstant +interlace+         #x0010)
(defconstant +double-scan+       #x0020)
(defconstant +c-sync+            #x0040)
(defconstant +c-sync-positive+   #x0080)
(defconstant +c-sync-negative+   #x0100)
(defconstant +h-skew-present+    #x0200)
(defconstant +b-cast+            #x0400)
(defconstant +pixel-multiplex+   #x0800)
(defconstant +double-clock+      #x1000)
(defconstant +clock-divide-by-2+ #x2000)

(defun get-screen-resources-1 (window rr-opcode)
  (let ((display (drawable-display window))
	(offset 4))
    (with-buffer-request-and-reply (display (opcode display) nil)
	((data rr-opcode)
	 (window window))
      (let* ((len (card32-get (pincf offset 4)))
	     (timestamp (card32-get (pincf offset 4)))
	     (config-timestamp (card32-get (pincf offset 4)))
	     (c (card16-get (pincf offset 2)))
	     (o (card16-get (pincf offset 2)))
	     (m (card16-get (pincf offset 2)))
	     (b (card16-get (pincf offset (+ 2 8))))
	     (crtcs (loop for i below c collect (card32-get (pincf offset 4))))
	     (outputs (loop for i below o collect (card32-get (pincf offset 4))))
	     (modeinfos (loop for i below m
			   collect (make-modeinfo :id (card32-get (pincf offset 4))
						  :width (card16-get (pincf offset 2))
						  :height (card16-get (pincf offset 2))
						  :dot-clock (card32-get (pincf offset 4))
						  :h-sync-start (card16-get (pincf offset 2))
						  :h-sync-end (card16-get (pincf offset 2))
						  :h-total (card16-get (pincf offset 2))
						  :h-skew (card16-get (pincf offset 2))
						  :v-sync-start (card16-get (pincf offset 2))
						  :v-sync-end (card16-get (pincf offset 2))
						  :v-total (card16-get (pincf offset 2))
						  :name (card16-get (pincf offset 2))
						  :mode-flags (card32-get (pincf offset 4))))))
	(loop for mi in modeinfos
	   do (let ((name-len (modeinfo-name mi)))
		(setf (modeinfo-name mi) (string-get name-len (pincf offset name-len)))))
	(values len timestamp config-timestamp c o m b crtcs outputs modeinfos)))))

(defun get-screen-resources (window)
  (get-screen-resources-1 window +screen-resources+))

(defun get-screen-resources-current (window)
  (get-screen-resources-1 window +screen-resources-current+))

(defun get-output-primary (window)
  (let ((display (drawable-display window)))
    (with-buffer-request-and-reply (display (opcode display) nil)
	((data +get-output-primary+)
	 (window window))
      (values (card32-get 8)))))

(defun get-output-info (display output timestamp)
  (let ((offset 1))
    (with-buffer-request-and-reply (display (opcode display) nil)
	((data +output-info+)
	 (card32 output)
	 (card32 timestamp))
      (let ((status (card8-get 0)))
	(values status)))))

(defun list-output-properties (display output)
  (let ((offset 8))
    (with-buffer-request-and-reply (display (opcode display) nil)
	((data +list-output-properties+)
	 (card32 output))
      (let ((natoms (card16-get (pincf offset 2))))
	(values natoms)))))

 #|
 (defvar *dpy* (open-display ""))
 (defvar *scr* (display-default-screen *dpy*))
 (defvar *root* (screen-root *scr*))

 (rr:query-version *dpy*)
 (rr:screen-info *root*)
 (loop for r in (list +inverted+ +right+ +left+ +normal+) do (rr:set-rotation *root* r) (sleep 5))
 |#
```

**Comment by xach** [comment]
I gave this a whirl but it doesn't compile for me. I get this:

    ; caught ERROR:
    ;   during macroexpansion of (MEMBER8-VECTOR-GET 1 +RR-CONFIG-STATUS+). Use *BREAK-ON-SIGNALS* to intercept.
    ;    The variable +RR-CONFIG-STATUS+ is unbound.

...a lot of times.

Reverting this commit for now.

**Comment by mgi** [comment]
Zach Beane <notifications@github.com> writes:

> I gave this a whirl but it doesn't compile for me. I get this:
>
>     ; caught ERROR:
>     ; during macroexpansion of (MEMBER8-VECTOR-GET 1
> +RR-CONFIG-STATUS+). Use *BREAK-ON-SIGNALS* to intercept.
>     ;    The variable +RR-CONFIG-STATUS+ is unbound.
>
> ...a lot of times.
>
> Reverting this commit for now.

There is a big (eval-when (:execute)) around those constant
definitions. I don't know why it is needed.
-- 
Manuel Giraud

**Comment by JMC-design** [comment]
Hey guys, sorry about that.  Some of it was older stuff that I was able to rescue from my harddrive when my computer blew up.  Just got a new computer this year (poor people problems) and still don't have a working development environment as working on a permaculture design.  Will fix it next month, but I'm pretty sure it's just that big eval-when surrounding the definitions.

**Comment by jorams** [comment]
Is there a reason this removes LispWorks support from the .asd file?

It also adds some spaces/tabs confusion, but I believe there's lots of that in CLX already.

**Comment by JMC-design** [comment]
It didn't quite 'remove' it.  Lispworks support wasn't added when I had downloaded the source and I had no internet access for about a year when I wrote it.  :)  Certainly made implementing parts of RandR from headers interesting.
As for spaces/tabs, I wrote it all in Emacs, so what ever it defaults to is what happened.  If there's a convention please let me know.  Sorry again, lot of problems caused because I couldn't afford a computer or internet access.  Finally got a computer for christmas and have since been trying to recover my 3 crashed harddrives :(  Haven't had the best of luck with computers these past couple of years.  
Will be interesting to see if Overlays works properly with my new nvidia graphics, since it wasn't working with amd.

**Comment by jorams** [comment]
The thing with tabs and spaces in CL is that the Common Lisp indentation conventions aren't really compatible with the variable width of a tab character.

Anyway, good luck with your computer troubles! Getting this ready and merged would be awesome.

**Pull request merged**
