### PR TITLE
Proposal for test suite.

### PR DESCRIPTION
**Pull request by ebrasca**
It is proposal test suite for clx.

### CODE REVIEW

**Comment by dkochmanski** [comment]
This is related to #41. Looks good to me as a starting point.

**Comment by PuercoPop** [comment]
@ebrasca Thanks for taking to time to tackle the lack of testing in CLX.

@dkochmanski I disagree strongly with that assessment. This is nowhere near a PR that is acceptable to merge. Due to the lack of mailing list, it may be a PR to show interest/effort towards completing the goal and request further feedback/guidance. However in the OP there are no questions of what they think is missing or what options of how to proceed are they pondering.

## Problems with this pull request

This PR only adds some boiler plate, some placeholder code but not even all the boiler plate needed, no test-op nor a test runner function, that runs all the tests of all the test packages. It removes test/image.lisp and test/trapezoid.lisp from clx.asd but didn't add it to the test system. Why remove them we are not migrating them to fiasco yet? It only reduces their visibility. They also should not be in the "XLIB" package but in a fiasco test-package. If we are not going to port them to fiasco yet, why touch them at all? Removing the export form only makes less clear the entry point. There shouldn't be any code in package.lisp files. Why two packages in the same file. `TEST-ASD` is clearly a placeholder function, Why commit that at all? And the commit message doesn't provides any context as to why any of this is done.

## How to get to a workable state

Although #41 lists to subsume current tests to the new test system, the current tests in CLX require visual verification to asses if the tests passed or not. More than a modicum amount of work is needed for them to be able to programmatically check if they passed or not. Maybe a smaller first step would be to create a window and verify it has been created. The test suite in addition of having test-packages should also have some code to setup test context and to help check/assert the state of the X server (number of windows, window-with-name-exists-p,etc). So a layout of the test suite would look something along the lines of

```
tests/
  utils.lisp ;; Setup code and assertion code
  basic.lisp ;; First tests
  ...
  input.lisp ;; After a while we should have a test per file/section of CLX
  ...
  extensions/
     ;; One test package per extension
  runner.lisp ;; A function to run all test-packages
```

As an example of setup code, we can see that `IMAGE-TEST` that creates a display variable and calls `OPEN-DEFAULT-DISPLAY` in `UNWIND-PROTECT` and class close-display at the end. This is something that we will need to do time and time again, so we can use something like


```lisp
;; Note: This function the unwind-protect form to cleanup the display afterwards
(defmacro with-x-server ((display screen root) (display-string) &body code)
  "Remove the boiler plate around connecting to an X server and running some
CODE in it."
  (with-gensyms (hostname display-id screen-id protocol)
    `(destructuring-bind (,hostname ,display-id ,screen-id ,protocol)
         (xlib::get-default-display ,display-string)
       (declare (ignore ,screen-id))
       (let* ((,display (xlib:open-display ,hostname :display ,display-id :protocol ,protocol))
              (,screen (xlib:display-default-screen ,display))
              (,root (xlib:screen-root ,screen)))
         (declare (ignorable ,root))
         ,@code))))
```

Or maybe something like define-x-test/define-test-with-xserver, which would expand to a deftest and the x server setup boiler plate.

**Comment by dkochmanski** [comment]
What I meant it's a good as a starting point for creating adding tests, but you are right.

**Comment by dkochmanski** [comment]
so what is state of this PR?

@ebrasca - are you planning to get back to it after #60 ?

**Comment by ebrasca** [comment]
Most likely, yes.

**Comment by ebrasca** [comment]
I stoped working on clx.
dkochmanski: I only understand test for functional programing.
Thanks you.

**Pull request closed without merging**
